version: "3.8"

networks:
  mynet:
    driver: bridge

services:
  mysql:
    image: mysql
    container_name: mysql
    hostname: 2366b6bd5e53
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jpa-approach
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_MAJOR: innovation
      MYSQL_VERSION: 9.1.0-1.el9
      MYSQL_SHELL_VERSION: 9.1.0-1.el9
      GOSU_VERSION: 1.17
    volumes:
      - D:/Learning/docker-storage/mysql:/var/lib/mysql
    restart: "no"
    networks:
      - mynet
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - mynet

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    image: product-service:latest
    ports:
      - "8082:8082"

    depends_on:
      - nexus
    environment:
      - JAVA_TOOL_OPTIONS=-Xms212m -Xmx212m -XX:ActiveProcessorCount=1
    restart: always
    deploy:
      resources:
        limits:
          memory: 300M
    networks:
      - mynet
  redis-master:
    image: redis:7.4-alpine
    container_name: redis-master
    ports:
      - "6379:6379"
    command: >
      redis-server
      --maxmemory 200mb
      --maxmemory-policy noeviction
      --appendonly yes
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.50"
    volumes:
      - D:\Learning\docker-storage\redis:/data
    restart: unless-stopped
    networks:
      - mynet

  redis-replica:
    image: redis:7.4-alpine
    container_name: redis-replica
    ports:
      - "6380:6379"
    command: >
      redis-server
      --maxmemory 200mb
      --maxmemory-policy noeviction
      --replicaof redis-master 6379
    deploy:
      resources:

        limits:
          memory: 256M
          cpus: "0.50"
    volumes:
      - D:\Learning\docker-storage\redis:/data
    restart: unless-stopped
    networks:
      - mynet
    depends_on:
      - redis-master

  redis-sentinel-1:
    image: redis:7.4-alpine
    container_name: redis-sentinel-1
    command: redis-sentinel /etc/redis/sentinel.conf
    volumes:
      - D:\Learning\docker-storage\redis-sentinel\sentinel.conf:/etc/redis/sentinel.conf
    ports:
      - "26379:26379"
    depends_on:
      - redis-master
    networks:
      - mynet

  redis-sentinel-2:
    image: redis:7.4-alpine
    container_name: redis-sentinel-2
    command: redis-sentinel /etc/redis/sentinel.conf
    volumes:
      - D:\Learning\docker-storage\redis-sentinel\sentinel.conf:/etc/redis/sentinel.conf
    ports:
      - "26380:26379"
    depends_on:
      - redis-master
    networks:
      - mynet

  redis-sentinel-3:
    image: redis:7.4-alpine
    container_name: redis-sentinel-3
    command: redis-sentinel /etc/redis/sentinel.conf
    volumes:
      - D:\Learning\docker-storage\redis-sentinel\sentinel.conf:/etc/redis/sentinel.conf
    ports:
      - "26381:26379"
    depends_on:
      - redis-master
    networks:
      - mynet

volumes:
  nexus-data:
