spring:
  application:
    name: common-cache
  data:
    redis:
      sentinel:
        master: mymaster
        nodes:
          - redis-sentinel-1:26379
          - redis-sentinel-2:26379
          - redis-sentinel-3:26379
      timeout: 2s
      lettuce:
        shutdown-timeout: 200ms

cache:
  redis:
    defaultTtl: 15m