

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://localhost:3306/jpa-approach/product_service
    username: admin
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true       # to show SQL in console
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  # (Optional) Logging settings for better Hibernate visibility
logging:
  level:
    org.hibernate.SQL: debug

server:
  port: 8080

